### ISSUE TITLE
Your Telegram bot tokens are exposed :)

### ISSUE THREAD

**Issue by Teraskull** [khify/bot_coronavirus_bot#1]
If those are real tokens, I suggest deleting the file, and changing your tokens.

**Comment by danylokaniev** [comment]
Omg. Thanks a lot. I forgot about token.

пт, 24 квіт. 2020, 23:44 користувач Anton Grouchtchak <
notifications@github.com> пише:

**Comment by Teraskull** [comment]
> Omg. Thanks a lot. I forgot about token.

No problem, but make sure to get a new token from botfather, as your token is still visible in the commits.
